// Plugin Docusaurus : Génère un fichier docsMetadata.json à partir des frontmatters des fichiers Markdown du dossier docs

const fs = require("fs");
const path = require("path");

/**
 * Extrait le frontmatter d'un contenu Markdown
 * @param {string} content
 * @returns {Object}
 */
function extractFrontmatter(content) {
  const match = content.match(/^---([\s\S]*?)---/);
  if (!match) return null;
  const frontmatter = {};
  match[1].split("\n").forEach((line) => {
    const [key, ...rest] = line.split(":");
    if (key && rest.length) {
      frontmatter[key.trim()] = rest.join(":").trim();
    }
  });
  return frontmatter;
}

/**
 * Retourne le chemin absolu du fichier docsMetadata.json dans static/
 * @returns {string}
 */
function getStaticMetadataPath() {
  return path.resolve(__dirname, "../../static/docsMetadata.json");
}

/**
 * Extrait les métadonnées (frontmatter) de tous les fichiers .md et .mdx d'un dossier, de manière récursive.
 * @param {Object} params
 * @param {string} params.docsDir - Chemin du dossier contenant les fichiers Markdown
 * @returns {Array<Object>} Tableau d'objets métadonnées
 */
function getAllDocsMetadata({ docsDir }) {
  const docs = [];

  function walk(currentDir, relativeParts = []) {
    const entries = fs.readdirSync(currentDir, { withFileTypes: true });
    for (const entry of entries) {
      const nextPath = path.join(currentDir, entry.name);
      const nextParts = [...relativeParts, entry.name];
      if (entry.isDirectory()) {
        walk(nextPath, nextParts);
        continue;
      }

      if (!entry.isFile() || (!entry.name.endsWith(".md") && !entry.name.endsWith(".mdx"))) {
        continue;
      }

      const content = fs.readFileSync(nextPath, "utf-8");
      const frontmatter = extractFrontmatter(content);
      if (!frontmatter) continue;

      const extension = path.extname(entry.name);
      const id = path
        .join(...relativeParts, entry.name)
        .replace(new RegExp(`\\${extension}$`), "");

      docs.push({
        id: id.split(path.sep).join("/"),
        ...frontmatter,
      });
    }
  }

  walk(docsDir);
  return docs;
}

/**
 * Extrait tous les objets avec tous les champs présents dans item pour les entrées de type 'doc',
 * et {id} pour 'autogenerated'.
 * @param {Array} items
 * @returns {Array<Object>}
 */
function extractAllDocEntries(items) {
  let entries = [];
  for (const item of items) {
    if (typeof item === "string") {
      entries.push({ id: item });
      continue;
    }
    if (item.type === "doc" && item.id) {
      entries.push({ ...item });
    } else if (item.type === "category" && Array.isArray(item.items)) {
      entries = entries.concat(extractAllDocEntries(item.items));
    } else if (item.type === "autogenerated" && item.dirName) {
      const dirPath = path.resolve(__dirname, `../../docs/${item.dirName}`);
      if (fs.existsSync(dirPath)) {
        const files = fs.readdirSync(dirPath);
        files.forEach((file) => {
          if (file.endsWith(".md")) {
            entries.push({ id: file.replace(/\.md$/, "") });
          }
        });
      }
    }
  }
  return entries;
}

/**
 * Génère le fichier sidebarDocs.js à partir de sidebars.js.
 *
 * Le dossier cible peut ne pas exister dans une version simplifiée du site.
 * On le crée donc explicitement pour éviter que le build Docusaurus échoue.
 */
function generateSidebarDocs() {
  const sidebarPath = path.resolve(__dirname, "../../sidebars.js");
  const outputPath = path.resolve(
    __dirname,
    "../../src/components/MainDocsGrid/sidebarDocs.js"
  );
  const outputDir = path.dirname(outputPath);

  fs.mkdirSync(outputDir, { recursive: true });

  const sidebars = require(sidebarPath);
  let allEntries = [];
  if (Array.isArray(sidebars.docs)) {
    allEntries = extractAllDocEntries(sidebars.docs);
  }
  const content =
    "// Ce fichier est généré automatiquement à partir de sidebars.js\n" +
    "export default " +
    JSON.stringify(allEntries, null, 2) +
    ";\n";
  fs.writeFileSync(outputPath, content);
}

/**
 * Plugin Docusaurus pour exposer les métadonnées des documents
 */
module.exports = function pluginDocsMetadata(context, options) {
  return {
    name: "docusaurus-plugin-docs-metadata",
    async loadContent() {
      const docsDir = path.resolve(__dirname, "../../docs");
      return getAllDocsMetadata({ docsDir });
    },
    async contentLoaded({ content }) {
      fs.writeFileSync(
        getStaticMetadataPath(),
        JSON.stringify(content, null, 2)
      );
      generateSidebarDocs();
    },
  };
};
